### ISSUE TITLE
Morning Peer-to-peer code review

### ISSUE THREAD

**Issue by VSeray** [RaviTejaM9602/Portfolio#12]

**Comment by VSeray** [comment]
Great work reaching this far 🎉
For your portfolio link I suggest you remove the id="home" from the homepage section to your works section. That way when someone clicks on the portfolio in the menu it would direct it to your works section.
Overall great job 😃

**Comment by RaviTejaM9602** [comment]
Thanks for letting me know about changing the link. 
![image](https://user-images.githubusercontent.com/72485137/145951404-5c4abfa2-fb8c-4f86-ab38-a42ecbb0a520.png)
Now it's working fine!!!!!!!
