### ISSUE TITLE
Morning session review

### ISSUE THREAD

**Issue by myelin0** [RaviTejaM9602/Portfolio#19]
Good job with the code  👍 ,but you can check some small issues:

- Please deploy your project with GitHub pages so people will be able to see your project.
- Please add your Twitter link page in the Readme file.
- Please add MIT.md to your portfolio for copyright issues.

**Comment by RaviTejaM9602** [comment]
Added MIT.md file, Twitter Link, Added Github Pages link for people who can view it.

**Comment by VTY1999** [comment]
**Good job on the project so far, there is only one issue you need to fix:**

- It would be nice if you deploy the project so people can view it.

**Comment by BereketRetta** [comment]
Good Job! I can't see any problems but improvement in deploying to the pages in Github would be great.
